### ISSUE TITLE
JSON data does not update (project.json, projects1.json)

### ISSUE THREAD

**Issue by pheix** [Raku/ecosystem#468]
Generic P6 modules database does not update or updates from wrong branch/commit.

Files [projects.json](https://ecosystem-api.p6c.org/projects.json) and [projects1.json](https://ecosystem-api.p6c.org/projects1.json) are frozen on @Kaiepi modules (that were removed in [July](https://github.com/perl6/ecosystem/commit/211201fac77b49a73f47e8a4b5eb99f0da8064a4)).

I have quick investigation and found out, that first [./updatelist.pl](https://github.com/perl6/ecosystem/blob/master/updatelist.pl) works locally (new modules included):

```sh
...
https://raw.githubusercontent.com/Demayl/perl6-Sys-IP/master/META6.json 200
https://raw.githubusercontent.com/tmtvl/neural-net/master/META6.json 200
https://raw.githubusercontent.com/antoniogamiz/Perl6-TypeGraph/master/META6.json 200
https://raw.githubusercontent.com/antoniogamiz/Pod-Utilities/master/META6.json 200
https://raw.githubusercontent.com/kjkuan/Proc-Feed/master/META6.json 200
https://raw.githubusercontent.com/dmaestro/Module-Pod/master/META6.json 200
https://raw.githubusercontent.com/oposs/jsonhound/master/META6.json 200
https://gitlab.com/pheix/lzw-revolunet-perl6/raw/master/META6.json 200
``` 

Second [./server/updatelist.pl](https://github.com/perl6/ecosystem/blob/master/server/updatelist.pl) works locally too (new modules included):

```sh
https://raw.githubusercontent.com/Demayl/perl6-Sys-IP/master/META6.json 200
https://raw.githubusercontent.com/tmtvl/neural-net/master/META6.json 200
https://raw.githubusercontent.com/antoniogamiz/Perl6-TypeGraph/master/META6.json 200
https://raw.githubusercontent.com/antoniogamiz/Pod-Utilities/master/META6.json 200
https://raw.githubusercontent.com/kjkuan/Proc-Feed/master/META6.json 200
https://raw.githubusercontent.com/dmaestro/Module-Pod/master/META6.json 200
https://raw.githubusercontent.com/oposs/jsonhound/master/META6.json 200
https://gitlab.com/pheix/lzw-revolunet-perl6/raw/master/META6.json 200
```

The 1st idea: something wrong with [./updatelist.pl](https://github.com/perl6/ecosystem/blob/master/updatelist.pl) on server. This script grabs [META.list](https://github.com/perl6/ecosystem/blob/master/META.list) from github. Maybe it's patched. 

The 2nd idea: repo was cloned to server, checked out on exact [commit](https://github.com/perl6/ecosystem/commit/12c3d27089f1adfeb1fa15868c4ff0cbafcdc8c5) and [./server/updatelist.pl](https://github.com/perl6/ecosystem/blob/master/server/updatelist.pl) parses this frozen META.list.

The 3rd idea: any other bug source))))

---

[zef](https://github.com/ugexe/zef) uses [projects1.json](https://ecosystem-api.p6c.org/projects1.json):

```sh
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: http://ecosystem-api.p6c.org/projects1.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
----------------------------------------------------
Content Storage                  |Distribution Count
----------------------------------------------------
Zef::Repository::LocalCache      |10                
Zef::Repository::Ecosystems<p6c> |861               
Zef::Repository::Ecosystems<cpan>|1393              
----------------------------------------------------
```

So, all new modules, added after 21, May are not available via this utility. Strange, that's none noticed that fact.

**Comment by JJ** [comment]
Thanks for the report. Will check it out

**Comment by ugexe** [comment]
The project file used by zef is generated by my own infrastructure/code and thus isn’t affected by this issue.

**Comment by ugexe** [comment]
Edit: the above is true for recent versions of zef. It appears you are not using the most recent version from before the infrastructure failures months ago.
