### ISSUE TITLE
Create a VSCode dev container for Raku

### ISSUE THREAD

**Issue by m-dango** [Raku/ecosystem#610]
The Dev Containers plugin in VSCode has a neat little dropdown which starts a docker container for you. I think it would be nice to create one for Raku. As an example, here is the config for the Perl container: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/perl

**Comment by JJ** [comment]
That might be a neat idea, but do you think this is the right place to make this request?

**Comment by m-dango** [comment]
Not sure. At the time of writing I wasn't sure where I wanted to put this, but I did want it in a Raku-focused location. Maybe [Raku/user-experience](https://github.com/Raku/user-experience) instead?

I can't seem to move it there, but I may resolve this myself sometime soon anyway.

**Comment by JJ** [comment]
> Not sure. At the time of writing I wasn't sure where I wanted to put this, but I did want it in a Raku-focused location. Maybe [Raku/user-experience](https://github.com/Raku/user-experience) instead?
> 
> I can't seem to move it there, but I may resolve this myself sometime soon anyway.

That would be great! Do you think we should create a specific repo under the Raku organization?

**Comment by m-dango** [comment]
Could be a good idea. It looks like the Perl example I referenced is marked as deprecated (https://containers.dev/templates), I'll look into what needs putting together. This looks like the current starting point: https://github.com/devcontainers/template-starter

**Comment by JJ** [comment]
I've re-created the repo from the existing template. I don't think the Perl template is a good starting point, anyway. You might want to take a look at [these containers](https://github.com/JJ/alpine-raku/)
