### ISSUE TITLE
[File::Temp] Add File::Temp to https://github.com/raku-community-modules

### ISSUE THREAD

**Issue by AntonOks** [Raku/ecosystem#619]
As this module is included in Rakudo Star, but seems somehow to be abandoned, see https://github.com/rbt/raku-File-Temp/issues/2, I suggest to safeguard it

**Comment by jonathanstowe** [comment]
I'm not sure we have a useful definition of _abandoned_ TBH,  @rbt appears to less prolific on GH than some, but maybe they've gone on a world cruise or something.  I'd suggest attempting to make contact with the author by other means than a GH issue as a first step.

There have been cases where stuff has been unilaterally re-assigned but IIRC this has been where the original author has completely disappeared and deleted their GH account.

**Comment by 2colours** [comment]
I think this issue can be closed now, @rbt passed ownership of that module to me. His last release will continue to live in the "zef ecosystem" and once a new release becomes necessary, I will release it myself.
@AntonOks

**Comment by AntonOks** [comment]
> I think this issue can be closed now, @rbt passed ownership of that module to me. His last release will continue to live in the "zef ecosystem" and once a new release becomes necessary, I will release it myself. @AntonOks

@2colours 
sound good.
where will you release it (in the future)?

**Comment by 2colours** [comment]
In the "zef ecosystem", as zef:2colours

**Comment by AntonOks** [comment]
> In the "zef ecosystem", as zef:2colours

well... any GIT repo, which hosts this module?

**Comment by 2colours** [comment]
Good sir, it's literally in the link in this issue... having said that, it shouldn't even really matter anymore. As https://github.com/tony-o/raku-fez/issues/108#issuecomment-1729479464 states, git repositories shouldn't be used as reference when the module is available via the "zef ecosystem", with author and version constraints enforced.

**Comment by 2colours** [comment]
Let's stick to the topic. We are releasing Raku here, and it seems to me that this issue has gone outdated.

**Comment by AntonOks** [comment]
> Let's stick to the topic. We are releasing Raku here, and it seems to me that this issue has gone outdated.
> 

Right, let's talk "Raku here". As I wrote in the other discussion...
```
  Also the Raku "core" dev team is doing so. Feel free to ask them what "git tags" do for them.

    https://github.com/rakudo/rakudo/tags
    https://github.com/Raku/nqp/tags
    https://github.com/MoarVM/MoarVM/tags
```

> (By the way, even if somebody does have a public git repository for a dist - which is absolutely not mandatory - it may or may not be hosted on a host that will be available all the time, it may even get deleted, or the commit history rewritten. We have seen the repositories of Patrick Spek go on and off, in which case you have zero control unless you mirrored the repositories, essentially taking up on a fez-complexity task.)

I know. And the Raku community has also some solutions for this kind of problem, which, btw., is a "common problem" with any kind of software:
- https://github.com/raku-community-modules
- https://github.com/scriptkitties
- https://github.com/Raku/ecosystem
- https://github.com/Raku/REA

From my take on it, FEZ is just the new (smarter) kid on the block. And you don't know what this kid will be once it grew up ;)

**Comment by JJ** [comment]
First, I'm not totally clear this discussion should take place here. Probably moving it to `problem-solving` would make more sense. I can do that if everyone is OK with that.
Meanwhile, from what I gather here, @AntonOks is asking to tag the releases, whether they've destined to be hosted in zef or anywhere else. As far as I can tell, [there's already a release tagged](https://github.com/2colours/raku-File-Temp/releases/tag/0.0.10), only it's quite outdated. Tagging the current release is literally issuing a couple of commands, @2colours , and it would really help the community since it's one of the releases included in the Rakudo Star distribution, which is the entry point to many new devs and users. So, would it be too much to ask to try and do it, since the repo seems to be active at the moment?

**Comment by AntonOks** [comment]
All I ask for from all Raku module developers is, please, whenever you change / update the "**version**" in your **META6.json**, also add a "git tag" with the same version string as in META6.json, so keep the various ways to refer to "verion changes" in sync.. That's all...

Most of the Rakudo dev's add a commit with the "version" changes in the META6.json file anyhow, so an additional "tag" is just max. 2 additional seconds of "work"...

Yes, we can continue the discussion wherever you want. For all those, who are on github, it could i.e. be https://github.com/rakudo/star/discussions/categories/star-modules

**Comment by 2colours** [comment]
So kindly, can this issue finally be closed now?

**Comment by JJ** [comment]
> Most of the Rakudo dev's add a commit with the "version" changes in the META6.json file anyhow, so an additional "tag" is just max. 2 additional seconds of "work"...
> 

As far as I'm concerned, I'll happily do it and thank you for your reminders to do so. Great work.
